version: "3.9"
services:
  server:
    build:
      context: .
    volumes:
      - .:/go/src/app
    environment:
      VIRTUAL_HOST: go-form.test
    networks:
      - nginx
      - default
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local

networks:
  nginx:
    name: nginx-proxy
    external: true

