#! /bin/bash

set -e

if [ -f .env ]; then
	set -a
	source .env
	set +a
fi

goose -dir migrations -s postgres "host=$DB_HOST user=$DB_USERNAME password=$DB_PASSWORD dbname=$DB_DATABASE sslmode=$DB_SSLMODE" $@
