// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package newdatabase

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Assignment struct {
	Id        int32            `db:"id"`
	Name      pgtype.Text      `db:"name"`
	Order     pgtype.Int4      `db:"order"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at"`
	Type      pgtype.Text      `db:"type"`
}

type DisplayableUser struct {
	Id          int32     `db:"id"`
	Name        string    `db:"name"`
	Email       string    `db:"email"`
	DateOfBirth time.Time `db:"date_of_birth"`
}

type ReloginToken struct {
	Id        int32            `db:"id"`
	Token     string           `db:"token"`
	UserID    int32            `db:"user_id"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
}

type User struct {
	Id          int32            `db:"id"`
	Email       string           `db:"email"`
	CreatedAt   pgtype.Timestamp `db:"created_at"`
	DateOfBirth time.Time        `db:"date_of_birth"`
	Name        string           `db:"name"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at"`
}
